declare const clavesUnidadesCatalog: Record<string, string>;
declare const formasPagoCatalog: Record<string, string>;
declare const impuestosCatalog: Record<string, string>;
declare const metodosPagoCatalog: Record<string, string>;
declare const monedasCatalog: Record<string, string>;
declare const regimenesFiscalesCatalog: Record<string, string>;
declare const tiposComprobantesCatalog: Record<string, string>;
declare const tiposRelacionesCatalog: Record<string, string>;
declare const usosCfdiCatalog: Record<string, string>;
export { clavesUnidadesCatalog, formasPagoCatalog, impuestosCatalog, metodosPagoCatalog, monedasCatalog, regimenesFiscalesCatalog, tiposComprobantesCatalog, tiposRelacionesCatalog, usosCfdiCatalog, };
